name: lumina
description: "Lumina: Funções em Jogo — aplicativo educacional para ensino e prática de funções de 1º e 2º grau."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

authors:
  - "Thulio Gamarano <thuliogamarano@gmail.com>"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.3.0
  fl_chart: ^0.60.0
  flutter_math_fork: ^0.7.4
  shared_preferences: ^2.0.18
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
